### ISSUE TITLE
Secure /notifications endpoint

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-search-api#14]
`POST /notifications` endpoint is totally open. We should protect it to prevent DoS and other similar attacks.

A simplistic option might be to register the endpoint to `update-api` with a per-instance random token created during build time, API startup or taken from configuration.

A more robust option would be to generate a random token for every subscription.

**Comment by hynek-urban** [comment]
I have implemented the suggested "robust solution" in #17.

However, there's one thing this doesn't solve - namely, anyone can create a hotel in the WT index, point its notificationUri to their server, let the search API subscribe for notifications there and use this subscription for flooding.

Despite that, I believe the solution should a) weed out the most naive attempts at flooding and b) at least limit the flooding to specific hotels only; a solution that can be extended by blacklisting or throttling in the future, should the need arise.

**Comment by hynek-urban** [comment]
Closing this issue as #17 has been merged to the develop branch.
